### ISSUE TITLE
[NEW] Bulk Delete Workaround

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-docs#25]
## Feedback
Would like to see an example of deleting all rows matching a specific criteria. That could also include matching against linked data. If that is possible?
Workaround for now filter out all ids matching a linked column and then make multiple calls to delete. Just felt a bit inefficient :)

## Route
https://xata.io/docs/api-guide/delete

## From
lindgr3n

Original issue: https://github.com/xataio/docs/issues/82

**Comment by joan-ing** [comment]
Transactions can be used for bulk deletion. "Transactions are used when deleting multiple records:” which is documented for delete, but can make this clearer

**Comment by SferaDev** [comment]
I think for this scenario, SQL is the best answer

**Comment by joan-ing** [comment]
Had a conversation with @SferaDev.  The SQL proxy limitation for this is a backend issue. Suggesting the following SQL based on Alexis and Kostas (suggestion in Discord)

`DELETE FROM titles
WHERE id IN (
    SELECT id
    FROM titles
    WHERE originalTitle ILIKE '%Matrix%'
    LIMIT 10000
);`
