### ISSUE TITLE
[FIX]: JSON type document sort limitation

### ISSUE THREAD

**Issue by kostasb** [xataio/mdx-docs#256]
### Where is the issue?

https://xata.io/docs/concepts/data-model#json
https://xata.io/docs/sdk/get#sorting-the-results

https://github.com/xataio/xata/issues/2979

### What's in the docs?

No references of limitations with sort

### What should be in the docs?

Known limitation: cannot sort by nested json fields.

**Comment by Rajakavitha1** [comment]
Closing this issue because it has been addressed in https://github.com/xataio/mdx-docs/pull/264
