### ISSUE TITLE
[NEW] Clarify how search filter links are used

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-docs#28]
Add docs note and example of using link in search filter to showcase how nested .id is not used there.

Relates to: https://github.com/xataio/client-ts/issues/896
From discord chat: https://discord.com/channels/996791218879086662/1002130113565053008/1073618555179905116

Original issue: https://github.com/xataio/docs/issues/78

**Comment by kostasb** [comment]
This is not required any more as, following a backend fix, filters work on link.id as documented now:

```
const records = await xata.search.all("sdk", {
  tables: [
    {
      table: "databases",
      filter: {
        "linked_workspace.id": "19v8n2",
      },
    },
  ],
});
```
