### ISSUE TITLE
Document content not formatted properly

### ISSUE THREAD

**Issue by yogendraapawar** [xataio/mdx-docs#319]
You can view the issue by heading over to this [link](https://xata.io/docs/api-reference/db/db_branch_name/tables/table_name/query#pagination).

![image](https://github.com/xataio/mdx-docs/assets/87609565/97a6601a-597f-4817-ab24-7425b38a4f4a)

The link 'Api Reference' under the offset pagination section [(Visit here)](https://xata.io/docs/sdk/get#offset-based-pagination) leads us to the page containing issue.

Thanks!

**Comment by philkra** [comment]
Thank you for reporting @yogendra131994, we'll fix the rendering issue.

**Comment by snide** [comment]
Fixed by https://github.com/xataio/mdx-docs/issues/319
