### ISSUE TITLE
[UPDATE]: Update existing docs to include file storage & image transformations

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-docs#60]
### Where is the issue?

In the docs preview https://xata-files.vercel.app/ (https://github.com/xataio/mdx-docs/pull/35), we are primarily pushing all the new documentation to the **File storage** section under **Concepts**. In reality, we're augmenting the architecture and adding support in a number of areas. We'll likely want to update a few pages to include file storage.

I'll defer to @joan-ing for how much should be broken out from the concept docs, but documenting some possiblities.

### What's in the docs?

We should consider updating the following:

**Overview**
https://xata.io/docs
File storage is now a core concept. We could consider updating the overview page to include the functionality we support (search, storage, AI, etc.)

**Serverless data platform**
https://xata.io/docs/concepts/serverless-data-platform
Similarly, file storage is now an extension of our data platform. We'll likely want to highlight this in a description of our Xata platform and update any architecture diagrams

**How Xata works**
https://xata.io/docs/concepts/how-it-works
Understanding _how_ our storage works is crucial for our users to trust us. This could live under the file storage concepts or more broadly in this page.

**TypeScript & Python SDKs**
https://xata.io/docs/typescript-client/overview
https://xata.io/docs/python-sdk/overview

We may also want to include image support under the TypeScript SDK. Either as a bullet under each section (getting records, etc.) and additionally image transformation support with examples for things like uploading files.

**Examples**
https://xata.io/docs/examples/starters-samples

@snide is working on an example and guide. We'll want to make sure the example is listed here.

I'm sure there's more, but in a quick scan of the docs, this felt like a good list.

**Comment by philkra** [comment]
🚢
